name: huri_whakatau

channels:
  - conda-forge

dependencies:
  - python=3.8
  - pip==21.1.1
  - ipykernel
  - beautifulsoup4==4.9.*
  - certifi==2020.12.5
  - chardet==4.0.0
  - click==7.1.2
  - cycler==0.10.0
  - Cython==0.29.14
  - gensim==3.8.3
  - idna==2.10
  - joblib==1.0.1
  - kiwisolver==1.3.1
  - lxml==4.6.*
  - matplotlib==3.3.4
  - nltk==3.5
  - numpy==1.20.1
  - pandas==1.2.4
  - Pillow==8.2.0
  - protobuf==3.15.6
  - PyMySQL==1.0.2
  - pyparsing==2.4.7
  - python-dateutil==2.8.1
  - pytz==2021.1
  - regex==2020.11.13
  - requests==2.25.1
  - scikit-learn==0.24.1
  - scipy==1.6.1
  - six==1.15.0
  - stanza==1.2
  - textblob==0.15.3
  - threadpoolctl==2.1.0
  - tqdm==4.58.0
  - typing-extensions==3.7.4.3
  - urllib3==1.26.5
  - vaderSentiment==3.3.2
  - wordcloud==1.8.1
  - pip:
    - smart-open==4.2.0
    - torch==1.8.0
